/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as EstimatorRouteImport } from './routes/estimator'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupervisorDisputesRouteImport } from './routes/supervisor/disputes'
import { Route as SupervisorDashboardRouteImport } from './routes/supervisor/dashboard'
import { Route as SupervisorAccountsRouteImport } from './routes/supervisor/accounts'
import { Route as OfficeUploadTemplateRouteImport } from './routes/office/upload-template'
import { Route as OfficeProfileRouteImport } from './routes/office/profile'
import { Route as OfficeNearbyRouteImport } from './routes/office/nearby'
import { Route as OfficeMessagesRouteImport } from './routes/office/messages'
import { Route as OfficeManageMilestonesRouteImport } from './routes/office/manage-milestones'
import { Route as OfficeHomeRouteImport } from './routes/office/home'
import { Route as OfficeDashboardRouteImport } from './routes/office/dashboard'
import { Route as OfficeContractSignRouteImport } from './routes/office/contract-sign'
import { Route as OfficeCatalogRouteImport } from './routes/office/catalog'
import { Route as OfficeBrowseRequestsRouteImport } from './routes/office/browse-requests'
import { Route as ClientTemplatesRouteImport } from './routes/client/templates'
import { Route as ClientSubmitRequestRouteImport } from './routes/client/submit-request'
import { Route as ClientSubmitReportRouteImport } from './routes/client/submit-report'
import { Route as ClientProjectTrackingRouteImport } from './routes/client/project-tracking'
import { Route as ClientMyRequestsRouteImport } from './routes/client/my-requests'
import { Route as ClientMilestoneApprovalRouteImport } from './routes/client/milestone-approval'
import { Route as ClientHomeRouteImport } from './routes/client/home'
import { Route as ClientEscrowRouteImport } from './routes/client/escrow'
import { Route as ClientDashboardRouteImport } from './routes/client/dashboard'
import { Route as ClientContractRouteImport } from './routes/client/contract'
import { Route as ClientCatalogRouteImport } from './routes/client/catalog'
import { Route as ClientBidsRouteImport } from './routes/client/bids'
import { Route as ClientBidComparisonRouteImport } from './routes/client/bid-comparison'
import { Route as TemplatesIdDetailsRouteImport } from './routes/templates/$id/details'
import { Route as SupervisorOfficeIdRouteImport } from './routes/supervisor/office.$id'
import { Route as SupervisorChatIdRouteImport } from './routes/supervisor/chat.$id'
import { Route as RequestsIdDetailsRouteImport } from './routes/requests/$id/details'
import { Route as RegistrationsIdDetailsRouteImport } from './routes/registrations/$id/details'
import { Route as OfficeRequestsIdRouteImport } from './routes/office/requests.$id'
import { Route as OfficeChatIdRouteImport } from './routes/office/chat.$id'
import { Route as DisputesIdDetailsRouteImport } from './routes/disputes/$id/details'
import { Route as ClientOfficeIdRouteImport } from './routes/client/office.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimatorRoute = EstimatorRouteImport.update({
  id: '/estimator',
  path: '/estimator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorDisputesRoute = SupervisorDisputesRouteImport.update({
  id: '/supervisor/disputes',
  path: '/supervisor/disputes',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorDashboardRoute = SupervisorDashboardRouteImport.update({
  id: '/supervisor/dashboard',
  path: '/supervisor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorAccountsRoute = SupervisorAccountsRouteImport.update({
  id: '/supervisor/accounts',
  path: '/supervisor/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeUploadTemplateRoute = OfficeUploadTemplateRouteImport.update({
  id: '/office/upload-template',
  path: '/office/upload-template',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeProfileRoute = OfficeProfileRouteImport.update({
  id: '/office/profile',
  path: '/office/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeNearbyRoute = OfficeNearbyRouteImport.update({
  id: '/office/nearby',
  path: '/office/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeMessagesRoute = OfficeMessagesRouteImport.update({
  id: '/office/messages',
  path: '/office/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeManageMilestonesRoute = OfficeManageMilestonesRouteImport.update({
  id: '/office/manage-milestones',
  path: '/office/manage-milestones',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeHomeRoute = OfficeHomeRouteImport.update({
  id: '/office/home',
  path: '/office/home',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeDashboardRoute = OfficeDashboardRouteImport.update({
  id: '/office/dashboard',
  path: '/office/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeContractSignRoute = OfficeContractSignRouteImport.update({
  id: '/office/contract-sign',
  path: '/office/contract-sign',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeCatalogRoute = OfficeCatalogRouteImport.update({
  id: '/office/catalog',
  path: '/office/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeBrowseRequestsRoute = OfficeBrowseRequestsRouteImport.update({
  id: '/office/browse-requests',
  path: '/office/browse-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientTemplatesRoute = ClientTemplatesRouteImport.update({
  id: '/client/templates',
  path: '/client/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientSubmitRequestRoute = ClientSubmitRequestRouteImport.update({
  id: '/client/submit-request',
  path: '/client/submit-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientSubmitReportRoute = ClientSubmitReportRouteImport.update({
  id: '/client/submit-report',
  path: '/client/submit-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientProjectTrackingRoute = ClientProjectTrackingRouteImport.update({
  id: '/client/project-tracking',
  path: '/client/project-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientMyRequestsRoute = ClientMyRequestsRouteImport.update({
  id: '/client/my-requests',
  path: '/client/my-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientMilestoneApprovalRoute = ClientMilestoneApprovalRouteImport.update({
  id: '/client/milestone-approval',
  path: '/client/milestone-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientHomeRoute = ClientHomeRouteImport.update({
  id: '/client/home',
  path: '/client/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientEscrowRoute = ClientEscrowRouteImport.update({
  id: '/client/escrow',
  path: '/client/escrow',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientDashboardRoute = ClientDashboardRouteImport.update({
  id: '/client/dashboard',
  path: '/client/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientContractRoute = ClientContractRouteImport.update({
  id: '/client/contract',
  path: '/client/contract',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientCatalogRoute = ClientCatalogRouteImport.update({
  id: '/client/catalog',
  path: '/client/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientBidsRoute = ClientBidsRouteImport.update({
  id: '/client/bids',
  path: '/client/bids',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientBidComparisonRoute = ClientBidComparisonRouteImport.update({
  id: '/client/bid-comparison',
  path: '/client/bid-comparison',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIdDetailsRoute = TemplatesIdDetailsRouteImport.update({
  id: '/templates/$id/details',
  path: '/templates/$id/details',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorOfficeIdRoute = SupervisorOfficeIdRouteImport.update({
  id: '/supervisor/office/$id',
  path: '/supervisor/office/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorChatIdRoute = SupervisorChatIdRouteImport.update({
  id: '/supervisor/chat/$id',
  path: '/supervisor/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIdDetailsRoute = RequestsIdDetailsRouteImport.update({
  id: '/requests/$id/details',
  path: '/requests/$id/details',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationsIdDetailsRoute = RegistrationsIdDetailsRouteImport.update({
  id: '/registrations/$id/details',
  path: '/registrations/$id/details',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeRequestsIdRoute = OfficeRequestsIdRouteImport.update({
  id: '/office/requests/$id',
  path: '/office/requests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeChatIdRoute = OfficeChatIdRouteImport.update({
  id: '/office/chat/$id',
  path: '/office/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DisputesIdDetailsRoute = DisputesIdDetailsRouteImport.update({
  id: '/disputes/$id/details',
  path: '/disputes/$id/details',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientOfficeIdRoute = ClientOfficeIdRouteImport.update({
  id: '/client/office/$id',
  path: '/client/office/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/estimator': typeof EstimatorRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/client/bid-comparison': typeof ClientBidComparisonRoute
  '/client/bids': typeof ClientBidsRoute
  '/client/catalog': typeof ClientCatalogRoute
  '/client/contract': typeof ClientContractRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/escrow': typeof ClientEscrowRoute
  '/client/home': typeof ClientHomeRoute
  '/client/milestone-approval': typeof ClientMilestoneApprovalRoute
  '/client/my-requests': typeof ClientMyRequestsRoute
  '/client/project-tracking': typeof ClientProjectTrackingRoute
  '/client/submit-report': typeof ClientSubmitReportRoute
  '/client/submit-request': typeof ClientSubmitRequestRoute
  '/client/templates': typeof ClientTemplatesRoute
  '/office/browse-requests': typeof OfficeBrowseRequestsRoute
  '/office/catalog': typeof OfficeCatalogRoute
  '/office/contract-sign': typeof OfficeContractSignRoute
  '/office/dashboard': typeof OfficeDashboardRoute
  '/office/home': typeof OfficeHomeRoute
  '/office/manage-milestones': typeof OfficeManageMilestonesRoute
  '/office/messages': typeof OfficeMessagesRoute
  '/office/nearby': typeof OfficeNearbyRoute
  '/office/profile': typeof OfficeProfileRoute
  '/office/upload-template': typeof OfficeUploadTemplateRoute
  '/supervisor/accounts': typeof SupervisorAccountsRoute
  '/supervisor/dashboard': typeof SupervisorDashboardRoute
  '/supervisor/disputes': typeof SupervisorDisputesRoute
  '/client/office/$id': typeof ClientOfficeIdRoute
  '/disputes/$id/details': typeof DisputesIdDetailsRoute
  '/office/chat/$id': typeof OfficeChatIdRoute
  '/office/requests/$id': typeof OfficeRequestsIdRoute
  '/registrations/$id/details': typeof RegistrationsIdDetailsRoute
  '/requests/$id/details': typeof RequestsIdDetailsRoute
  '/supervisor/chat/$id': typeof SupervisorChatIdRoute
  '/supervisor/office/$id': typeof SupervisorOfficeIdRoute
  '/templates/$id/details': typeof TemplatesIdDetailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/estimator': typeof EstimatorRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/client/bid-comparison': typeof ClientBidComparisonRoute
  '/client/bids': typeof ClientBidsRoute
  '/client/catalog': typeof ClientCatalogRoute
  '/client/contract': typeof ClientContractRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/escrow': typeof ClientEscrowRoute
  '/client/home': typeof ClientHomeRoute
  '/client/milestone-approval': typeof ClientMilestoneApprovalRoute
  '/client/my-requests': typeof ClientMyRequestsRoute
  '/client/project-tracking': typeof ClientProjectTrackingRoute
  '/client/submit-report': typeof ClientSubmitReportRoute
  '/client/submit-request': typeof ClientSubmitRequestRoute
  '/client/templates': typeof ClientTemplatesRoute
  '/office/browse-requests': typeof OfficeBrowseRequestsRoute
  '/office/catalog': typeof OfficeCatalogRoute
  '/office/contract-sign': typeof OfficeContractSignRoute
  '/office/dashboard': typeof OfficeDashboardRoute
  '/office/home': typeof OfficeHomeRoute
  '/office/manage-milestones': typeof OfficeManageMilestonesRoute
  '/office/messages': typeof OfficeMessagesRoute
  '/office/nearby': typeof OfficeNearbyRoute
  '/office/profile': typeof OfficeProfileRoute
  '/office/upload-template': typeof OfficeUploadTemplateRoute
  '/supervisor/accounts': typeof SupervisorAccountsRoute
  '/supervisor/dashboard': typeof SupervisorDashboardRoute
  '/supervisor/disputes': typeof SupervisorDisputesRoute
  '/client/office/$id': typeof ClientOfficeIdRoute
  '/disputes/$id/details': typeof DisputesIdDetailsRoute
  '/office/chat/$id': typeof OfficeChatIdRoute
  '/office/requests/$id': typeof OfficeRequestsIdRoute
  '/registrations/$id/details': typeof RegistrationsIdDetailsRoute
  '/requests/$id/details': typeof RequestsIdDetailsRoute
  '/supervisor/chat/$id': typeof SupervisorChatIdRoute
  '/supervisor/office/$id': typeof SupervisorOfficeIdRoute
  '/templates/$id/details': typeof TemplatesIdDetailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/estimator': typeof EstimatorRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/client/bid-comparison': typeof ClientBidComparisonRoute
  '/client/bids': typeof ClientBidsRoute
  '/client/catalog': typeof ClientCatalogRoute
  '/client/contract': typeof ClientContractRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/escrow': typeof ClientEscrowRoute
  '/client/home': typeof ClientHomeRoute
  '/client/milestone-approval': typeof ClientMilestoneApprovalRoute
  '/client/my-requests': typeof ClientMyRequestsRoute
  '/client/project-tracking': typeof ClientProjectTrackingRoute
  '/client/submit-report': typeof ClientSubmitReportRoute
  '/client/submit-request': typeof ClientSubmitRequestRoute
  '/client/templates': typeof ClientTemplatesRoute
  '/office/browse-requests': typeof OfficeBrowseRequestsRoute
  '/office/catalog': typeof OfficeCatalogRoute
  '/office/contract-sign': typeof OfficeContractSignRoute
  '/office/dashboard': typeof OfficeDashboardRoute
  '/office/home': typeof OfficeHomeRoute
  '/office/manage-milestones': typeof OfficeManageMilestonesRoute
  '/office/messages': typeof OfficeMessagesRoute
  '/office/nearby': typeof OfficeNearbyRoute
  '/office/profile': typeof OfficeProfileRoute
  '/office/upload-template': typeof OfficeUploadTemplateRoute
  '/supervisor/accounts': typeof SupervisorAccountsRoute
  '/supervisor/dashboard': typeof SupervisorDashboardRoute
  '/supervisor/disputes': typeof SupervisorDisputesRoute
  '/client/office/$id': typeof ClientOfficeIdRoute
  '/disputes/$id/details': typeof DisputesIdDetailsRoute
  '/office/chat/$id': typeof OfficeChatIdRoute
  '/office/requests/$id': typeof OfficeRequestsIdRoute
  '/registrations/$id/details': typeof RegistrationsIdDetailsRoute
  '/requests/$id/details': typeof RequestsIdDetailsRoute
  '/supervisor/chat/$id': typeof SupervisorChatIdRoute
  '/supervisor/office/$id': typeof SupervisorOfficeIdRoute
  '/templates/$id/details': typeof TemplatesIdDetailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/estimator'
    | '/forbidden'
    | '/login'
    | '/notifications'
    | '/register'
    | '/client/bid-comparison'
    | '/client/bids'
    | '/client/catalog'
    | '/client/contract'
    | '/client/dashboard'
    | '/client/escrow'
    | '/client/home'
    | '/client/milestone-approval'
    | '/client/my-requests'
    | '/client/project-tracking'
    | '/client/submit-report'
    | '/client/submit-request'
    | '/client/templates'
    | '/office/browse-requests'
    | '/office/catalog'
    | '/office/contract-sign'
    | '/office/dashboard'
    | '/office/home'
    | '/office/manage-milestones'
    | '/office/messages'
    | '/office/nearby'
    | '/office/profile'
    | '/office/upload-template'
    | '/supervisor/accounts'
    | '/supervisor/dashboard'
    | '/supervisor/disputes'
    | '/client/office/$id'
    | '/disputes/$id/details'
    | '/office/chat/$id'
    | '/office/requests/$id'
    | '/registrations/$id/details'
    | '/requests/$id/details'
    | '/supervisor/chat/$id'
    | '/supervisor/office/$id'
    | '/templates/$id/details'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/estimator'
    | '/forbidden'
    | '/login'
    | '/notifications'
    | '/register'
    | '/client/bid-comparison'
    | '/client/bids'
    | '/client/catalog'
    | '/client/contract'
    | '/client/dashboard'
    | '/client/escrow'
    | '/client/home'
    | '/client/milestone-approval'
    | '/client/my-requests'
    | '/client/project-tracking'
    | '/client/submit-report'
    | '/client/submit-request'
    | '/client/templates'
    | '/office/browse-requests'
    | '/office/catalog'
    | '/office/contract-sign'
    | '/office/dashboard'
    | '/office/home'
    | '/office/manage-milestones'
    | '/office/messages'
    | '/office/nearby'
    | '/office/profile'
    | '/office/upload-template'
    | '/supervisor/accounts'
    | '/supervisor/dashboard'
    | '/supervisor/disputes'
    | '/client/office/$id'
    | '/disputes/$id/details'
    | '/office/chat/$id'
    | '/office/requests/$id'
    | '/registrations/$id/details'
    | '/requests/$id/details'
    | '/supervisor/chat/$id'
    | '/supervisor/office/$id'
    | '/templates/$id/details'
  id:
    | '__root__'
    | '/'
    | '/estimator'
    | '/forbidden'
    | '/login'
    | '/notifications'
    | '/register'
    | '/client/bid-comparison'
    | '/client/bids'
    | '/client/catalog'
    | '/client/contract'
    | '/client/dashboard'
    | '/client/escrow'
    | '/client/home'
    | '/client/milestone-approval'
    | '/client/my-requests'
    | '/client/project-tracking'
    | '/client/submit-report'
    | '/client/submit-request'
    | '/client/templates'
    | '/office/browse-requests'
    | '/office/catalog'
    | '/office/contract-sign'
    | '/office/dashboard'
    | '/office/home'
    | '/office/manage-milestones'
    | '/office/messages'
    | '/office/nearby'
    | '/office/profile'
    | '/office/upload-template'
    | '/supervisor/accounts'
    | '/supervisor/dashboard'
    | '/supervisor/disputes'
    | '/client/office/$id'
    | '/disputes/$id/details'
    | '/office/chat/$id'
    | '/office/requests/$id'
    | '/registrations/$id/details'
    | '/requests/$id/details'
    | '/supervisor/chat/$id'
    | '/supervisor/office/$id'
    | '/templates/$id/details'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EstimatorRoute: typeof EstimatorRoute
  ForbiddenRoute: typeof ForbiddenRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  RegisterRoute: typeof RegisterRoute
  ClientBidComparisonRoute: typeof ClientBidComparisonRoute
  ClientBidsRoute: typeof ClientBidsRoute
  ClientCatalogRoute: typeof ClientCatalogRoute
  ClientContractRoute: typeof ClientContractRoute
  ClientDashboardRoute: typeof ClientDashboardRoute
  ClientEscrowRoute: typeof ClientEscrowRoute
  ClientHomeRoute: typeof ClientHomeRoute
  ClientMilestoneApprovalRoute: typeof ClientMilestoneApprovalRoute
  ClientMyRequestsRoute: typeof ClientMyRequestsRoute
  ClientProjectTrackingRoute: typeof ClientProjectTrackingRoute
  ClientSubmitReportRoute: typeof ClientSubmitReportRoute
  ClientSubmitRequestRoute: typeof ClientSubmitRequestRoute
  ClientTemplatesRoute: typeof ClientTemplatesRoute
  OfficeBrowseRequestsRoute: typeof OfficeBrowseRequestsRoute
  OfficeCatalogRoute: typeof OfficeCatalogRoute
  OfficeContractSignRoute: typeof OfficeContractSignRoute
  OfficeDashboardRoute: typeof OfficeDashboardRoute
  OfficeHomeRoute: typeof OfficeHomeRoute
  OfficeManageMilestonesRoute: typeof OfficeManageMilestonesRoute
  OfficeMessagesRoute: typeof OfficeMessagesRoute
  OfficeNearbyRoute: typeof OfficeNearbyRoute
  OfficeProfileRoute: typeof OfficeProfileRoute
  OfficeUploadTemplateRoute: typeof OfficeUploadTemplateRoute
  SupervisorAccountsRoute: typeof SupervisorAccountsRoute
  SupervisorDashboardRoute: typeof SupervisorDashboardRoute
  SupervisorDisputesRoute: typeof SupervisorDisputesRoute
  ClientOfficeIdRoute: typeof ClientOfficeIdRoute
  DisputesIdDetailsRoute: typeof DisputesIdDetailsRoute
  OfficeChatIdRoute: typeof OfficeChatIdRoute
  OfficeRequestsIdRoute: typeof OfficeRequestsIdRoute
  RegistrationsIdDetailsRoute: typeof RegistrationsIdDetailsRoute
  RequestsIdDetailsRoute: typeof RequestsIdDetailsRoute
  SupervisorChatIdRoute: typeof SupervisorChatIdRoute
  SupervisorOfficeIdRoute: typeof SupervisorOfficeIdRoute
  TemplatesIdDetailsRoute: typeof TemplatesIdDetailsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimator': {
      id: '/estimator'
      path: '/estimator'
      fullPath: '/estimator'
      preLoaderRoute: typeof EstimatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor/disputes': {
      id: '/supervisor/disputes'
      path: '/supervisor/disputes'
      fullPath: '/supervisor/disputes'
      preLoaderRoute: typeof SupervisorDisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor/dashboard': {
      id: '/supervisor/dashboard'
      path: '/supervisor/dashboard'
      fullPath: '/supervisor/dashboard'
      preLoaderRoute: typeof SupervisorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor/accounts': {
      id: '/supervisor/accounts'
      path: '/supervisor/accounts'
      fullPath: '/supervisor/accounts'
      preLoaderRoute: typeof SupervisorAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/upload-template': {
      id: '/office/upload-template'
      path: '/office/upload-template'
      fullPath: '/office/upload-template'
      preLoaderRoute: typeof OfficeUploadTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/profile': {
      id: '/office/profile'
      path: '/office/profile'
      fullPath: '/office/profile'
      preLoaderRoute: typeof OfficeProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/nearby': {
      id: '/office/nearby'
      path: '/office/nearby'
      fullPath: '/office/nearby'
      preLoaderRoute: typeof OfficeNearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/messages': {
      id: '/office/messages'
      path: '/office/messages'
      fullPath: '/office/messages'
      preLoaderRoute: typeof OfficeMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/manage-milestones': {
      id: '/office/manage-milestones'
      path: '/office/manage-milestones'
      fullPath: '/office/manage-milestones'
      preLoaderRoute: typeof OfficeManageMilestonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/home': {
      id: '/office/home'
      path: '/office/home'
      fullPath: '/office/home'
      preLoaderRoute: typeof OfficeHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/dashboard': {
      id: '/office/dashboard'
      path: '/office/dashboard'
      fullPath: '/office/dashboard'
      preLoaderRoute: typeof OfficeDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/contract-sign': {
      id: '/office/contract-sign'
      path: '/office/contract-sign'
      fullPath: '/office/contract-sign'
      preLoaderRoute: typeof OfficeContractSignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/catalog': {
      id: '/office/catalog'
      path: '/office/catalog'
      fullPath: '/office/catalog'
      preLoaderRoute: typeof OfficeCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/browse-requests': {
      id: '/office/browse-requests'
      path: '/office/browse-requests'
      fullPath: '/office/browse-requests'
      preLoaderRoute: typeof OfficeBrowseRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/templates': {
      id: '/client/templates'
      path: '/client/templates'
      fullPath: '/client/templates'
      preLoaderRoute: typeof ClientTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/submit-request': {
      id: '/client/submit-request'
      path: '/client/submit-request'
      fullPath: '/client/submit-request'
      preLoaderRoute: typeof ClientSubmitRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/submit-report': {
      id: '/client/submit-report'
      path: '/client/submit-report'
      fullPath: '/client/submit-report'
      preLoaderRoute: typeof ClientSubmitReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/project-tracking': {
      id: '/client/project-tracking'
      path: '/client/project-tracking'
      fullPath: '/client/project-tracking'
      preLoaderRoute: typeof ClientProjectTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/my-requests': {
      id: '/client/my-requests'
      path: '/client/my-requests'
      fullPath: '/client/my-requests'
      preLoaderRoute: typeof ClientMyRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/milestone-approval': {
      id: '/client/milestone-approval'
      path: '/client/milestone-approval'
      fullPath: '/client/milestone-approval'
      preLoaderRoute: typeof ClientMilestoneApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/home': {
      id: '/client/home'
      path: '/client/home'
      fullPath: '/client/home'
      preLoaderRoute: typeof ClientHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/escrow': {
      id: '/client/escrow'
      path: '/client/escrow'
      fullPath: '/client/escrow'
      preLoaderRoute: typeof ClientEscrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/dashboard': {
      id: '/client/dashboard'
      path: '/client/dashboard'
      fullPath: '/client/dashboard'
      preLoaderRoute: typeof ClientDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/contract': {
      id: '/client/contract'
      path: '/client/contract'
      fullPath: '/client/contract'
      preLoaderRoute: typeof ClientContractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/catalog': {
      id: '/client/catalog'
      path: '/client/catalog'
      fullPath: '/client/catalog'
      preLoaderRoute: typeof ClientCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/bids': {
      id: '/client/bids'
      path: '/client/bids'
      fullPath: '/client/bids'
      preLoaderRoute: typeof ClientBidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/bid-comparison': {
      id: '/client/bid-comparison'
      path: '/client/bid-comparison'
      fullPath: '/client/bid-comparison'
      preLoaderRoute: typeof ClientBidComparisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$id/details': {
      id: '/templates/$id/details'
      path: '/templates/$id/details'
      fullPath: '/templates/$id/details'
      preLoaderRoute: typeof TemplatesIdDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor/office/$id': {
      id: '/supervisor/office/$id'
      path: '/supervisor/office/$id'
      fullPath: '/supervisor/office/$id'
      preLoaderRoute: typeof SupervisorOfficeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor/chat/$id': {
      id: '/supervisor/chat/$id'
      path: '/supervisor/chat/$id'
      fullPath: '/supervisor/chat/$id'
      preLoaderRoute: typeof SupervisorChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$id/details': {
      id: '/requests/$id/details'
      path: '/requests/$id/details'
      fullPath: '/requests/$id/details'
      preLoaderRoute: typeof RequestsIdDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrations/$id/details': {
      id: '/registrations/$id/details'
      path: '/registrations/$id/details'
      fullPath: '/registrations/$id/details'
      preLoaderRoute: typeof RegistrationsIdDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/requests/$id': {
      id: '/office/requests/$id'
      path: '/office/requests/$id'
      fullPath: '/office/requests/$id'
      preLoaderRoute: typeof OfficeRequestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/chat/$id': {
      id: '/office/chat/$id'
      path: '/office/chat/$id'
      fullPath: '/office/chat/$id'
      preLoaderRoute: typeof OfficeChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disputes/$id/details': {
      id: '/disputes/$id/details'
      path: '/disputes/$id/details'
      fullPath: '/disputes/$id/details'
      preLoaderRoute: typeof DisputesIdDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/office/$id': {
      id: '/client/office/$id'
      path: '/client/office/$id'
      fullPath: '/client/office/$id'
      preLoaderRoute: typeof ClientOfficeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EstimatorRoute: EstimatorRoute,
  ForbiddenRoute: ForbiddenRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  RegisterRoute: RegisterRoute,
  ClientBidComparisonRoute: ClientBidComparisonRoute,
  ClientBidsRoute: ClientBidsRoute,
  ClientCatalogRoute: ClientCatalogRoute,
  ClientContractRoute: ClientContractRoute,
  ClientDashboardRoute: ClientDashboardRoute,
  ClientEscrowRoute: ClientEscrowRoute,
  ClientHomeRoute: ClientHomeRoute,
  ClientMilestoneApprovalRoute: ClientMilestoneApprovalRoute,
  ClientMyRequestsRoute: ClientMyRequestsRoute,
  ClientProjectTrackingRoute: ClientProjectTrackingRoute,
  ClientSubmitReportRoute: ClientSubmitReportRoute,
  ClientSubmitRequestRoute: ClientSubmitRequestRoute,
  ClientTemplatesRoute: ClientTemplatesRoute,
  OfficeBrowseRequestsRoute: OfficeBrowseRequestsRoute,
  OfficeCatalogRoute: OfficeCatalogRoute,
  OfficeContractSignRoute: OfficeContractSignRoute,
  OfficeDashboardRoute: OfficeDashboardRoute,
  OfficeHomeRoute: OfficeHomeRoute,
  OfficeManageMilestonesRoute: OfficeManageMilestonesRoute,
  OfficeMessagesRoute: OfficeMessagesRoute,
  OfficeNearbyRoute: OfficeNearbyRoute,
  OfficeProfileRoute: OfficeProfileRoute,
  OfficeUploadTemplateRoute: OfficeUploadTemplateRoute,
  SupervisorAccountsRoute: SupervisorAccountsRoute,
  SupervisorDashboardRoute: SupervisorDashboardRoute,
  SupervisorDisputesRoute: SupervisorDisputesRoute,
  ClientOfficeIdRoute: ClientOfficeIdRoute,
  DisputesIdDetailsRoute: DisputesIdDetailsRoute,
  OfficeChatIdRoute: OfficeChatIdRoute,
  OfficeRequestsIdRoute: OfficeRequestsIdRoute,
  RegistrationsIdDetailsRoute: RegistrationsIdDetailsRoute,
  RequestsIdDetailsRoute: RequestsIdDetailsRoute,
  SupervisorChatIdRoute: SupervisorChatIdRoute,
  SupervisorOfficeIdRoute: SupervisorOfficeIdRoute,
  TemplatesIdDetailsRoute: TemplatesIdDetailsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
